[py4kids](https://github.com/wgong/py4kids)

# Functions and Modules


In this lesson, we learn the building blocks of python:
* Function - named collection of python statements
* Module - a named file with functions, variables (you may call it package, library)

The purpose to write modular codes and to reuse (recycle).

<img src=../images/008-form-and-function.jpg width=70%>

In [1]:
from jyquickhelper import add_notebook_menu
add_notebook_menu()

## Function

Function is useful, it has specific functionality. It has the following parts:

* keyword __<font color=red>def</font>__ defines a function;
* function has a name: create_a_number_list, it should be meanful;
* function may have input parameters, e.g. start,stop, stride
* function has a body, which implements functionality of the function

In [2]:
# this function does nothing
def dummy_function():
    pass

In [3]:
print(dummy_function())

None


In [4]:
dummy_function()

In [5]:
dummy_function()

In [6]:
def greeting(name):
    if name:
        print('Hi, %s' % name)
    else:
        print("name is blank")

In [7]:
# test
g = greeting('Allen')

Hi, Allen


In [8]:
print(g)

None


In [9]:
greeting('Teacher')

Hi, Teacher


In [10]:
greeting("")

name is blank


In [11]:
print(range(10))

range(0, 10)


In [12]:
# this function creates a list of integer numbers
def create_integer_list(start, stop, stride=1):
    rg = range(start, stop, stride)
    lst = list(rg)
    return lst
    #return list(range(start, stop, stride))

In [13]:
print(create_integer_list(0,10,3))

[0, 3, 6, 9]


In [14]:
print(create_integer_list(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [15]:
print(create_integer_list(0,10,0))

ValueError: range() arg 3 must not be zero

In [16]:
print(create_integer_list(10,1,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2]


In [17]:
# numerical python
import numpy as np

In [18]:
#import numpy
#numpy.arange(1., 100., 0.1)

In [19]:
np.arange(0.2, 1, 0.1)

array([ 0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [20]:
def create_real_list(start, stop, stride):
    import numpy as np
    return np.arange(start, stop, stride)

In [23]:
create_real_list(0.2, 1, 0.1)

array([ 0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [24]:
# this function has error handling to avoid crash
def create_real_list2(start, stop, stride):
    import numpy as np
    if stride != 0.0:
        return np.arange(start, stop, stride)
    else:
        print('[ERROR] stride is zero')
        return None

In [25]:
create_real_list2(-0.1,2.0,0.2)

array([-0.1,  0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9])

In [26]:
create_real_list2(-0.1,2.0,0)

[ERROR] stride is zero


### variable scope

In [27]:
eng_name = "Mr Wang"
chn_name = u"老王"

In [28]:
all(u'\u4e00' <= c <= u'\u9fff' for c in eng_name)

False

In [29]:
all(u'\u4e00' <= c <= u'\u9fff' for c in chn_name)

True

In [30]:
# this function is useful to detect if a string is written in Chinese
def is_chinese(s):
    return all(u'\u4e00' <= c <= u'\u9fff' for c in s)

In [31]:
is_chinese(chn_name)

True

In [32]:
def greeting2(name):
    lang_dic = {'chn':'你好', 'eng':'Hello'}
    if is_chinese(name):
        print(lang_dic['chn'], ', ', name)
    else:
        print(lang_dic['eng'], ', ', name)

In [33]:
greeting2(chn_name)

你好 ,  老王


In [34]:
greeting2(eng_name)

Hello ,  Mr Wang


In [35]:
lang_dic

NameError: name 'lang_dic' is not defined

any variable defined inside a function is called local variable

In [36]:
g_lang_dic = {'chn':'您好', 'eng':'Hello'}
def greeting3(name):
    if is_chinese(name):
        print(g_lang_dic['chn'], ', ', name)
    else:
        print(g_lang_dic['eng'], ', ', name)

In [37]:
g_lang_dic

{'chn': '您好', 'eng': 'Hello'}

In [38]:
greeting3(chn_name)

您好 ,  老王


g_lang_dic is a global variable

### math formula

#### [quadratic equation](https://www.wikiwand.com/en/Quadratic_equation)

$ a \cdot x^2 + b \cdot x + c = 0 $

$ x = \frac{-b \pm \sqrt{b^2-4ac}}{2a} $

In [39]:
def quad_eq(a, b, c):
    """
    Solving a quadratic equation:
        https://www.wikiwand.com/en/Quadratic_equation
    """
    if a == 0.0:
        if b == 0.0:
            print('Both a and b are zero, no solution')
            return None
        else:
            x = - c/b
            return x
    else:
        import math
        x1 = (-b + math.sqrt(b**2 - 4*a*c)) / (2.0*a) 
        x2 = (-b - math.sqrt(b**2 - 4*a*c)) / (2.0*a) 
        return [x1, x2]

We need to test it for various cases

In [40]:
print(quad_eq(1,-2,1))

[1.0, 1.0]


In [41]:
print(quad_eq(1,2,3))

ValueError: math domain error

In [42]:
print(quad_eq(1,5,5))

[-1.381966011250105, -3.618033988749895]


In [43]:
print(quad_eq(0,0,1))

Both a and b are zero, no solution
None


#### [The Pythagorean Theorem](http://www.montereyinstitute.org/courses/DevelopmentalMath/COURSE_TEXT2_RESOURCE/U07_L1_T4_text_final.html)

$ a^2 + b^2 = c^2 $

<img src=../images/008-Pythagoras.svg.png width=50%>

In [44]:
def pythagorean(a,b,c):
    import math
    if c is None and a is not None and b is not None:
        return math.sqrt(a**2 + b**2)
    elif a is None and b is not None and c is not None and c >= b:
        return math.sqrt(c**2 - b**2)
    elif b is None and a is not None and c is not None and c >= a:
        return math.sqrt(c**2 - a**2)
    else:
        return "No solution"

Test time

In [45]:
print(pythagorean(3,4,None))

5.0


In [46]:
print(pythagorean(None,4,5))

3.0


In [47]:
print(pythagorean(None,5,5))

0.0


In [48]:
print(pythagorean(None,7,5))

No solution


## Module

Modules are used to group functions, variables, and other things
together into larger, more powerful programs.

Module is like Lego

In [49]:
import py4kids as mm

In [50]:
print(mm.version)

1.0


In [51]:
print(mm.g_lang_dic)

{'eng': 'Hello', 'chn': '您好'}


In [52]:
mm.greeting('Frank')

Hi, Frank


In [53]:
mm.create_real_list(1.1, 9.1, 0.3)

array([ 1.1,  1.4,  1.7,  2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,
        4.4,  4.7,  5. ,  5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,
        7.7,  8. ,  8.3,  8.6,  8.9])

In [54]:
monkey = '孙悟空'
mm.greeting3(monkey)

您好 ,  孙悟空


In [55]:
mm.quad_eq(1,-6,9)

[3.0, 3.0]

In [56]:
mm.pythagorean(5,12,None)

13.0

### [pygame](https://www.pygame.org/news)

<img src=../images/008-Pygame_logo.png width=70%>

<img src=../images/008-site-packages.jpg width=70%>

<img src=../images/008-pygame.JPG width=70%>

open a terminal, go to pygame examples folder

to install 
CMD> conda install pygame

On Windows:
```
CMD> c:
CMD> cd C:\Anaconda3\Lib\site-packages\pygame\examples
CMD> python chimp.py
```

On Mac or Unix:
```
CMD> cd ~\Anaconda3\Lib\site-packages\pygame\examples
CMD> python chimp.py
```

## Reference

[Learning Python: From Zero to Hero](https://medium.freecodecamp.org/learning-python-from-zero-to-hero-120ea540b567) is a useful review of basic python

### Gemini 


*What are Prime Numbers?**

A prime number is a positive integer that is divisible only by itself and 1. In other words, the only factors of a prime number 
are 1 and the number itself.

For example, 2, 3, 5, 7, 11, and 13 are all prime numbers because they can only be divided evenly by 1 and themselves.

**Why are Prime Numbers Important?**

Prime numbers play a crucial role in many areas of mathematics, science, and engineering. Here are a few reasons why:

1. **Cryptography**: Prime numbers are used to develop secure encryption algorithms, such as RSA (Rivest-Shamir-Adleman) and 
elliptic curve cryptography.
2. **Computer Science**: Prime numbers are essential in computer science, particularly in the study of algorithms, data 
compression, and error-correcting codes.
3. **Number Theory**: Prime numbers have deep connections to other areas of number theory, such as modular forms, elliptic 
curves, and the distribution of prime numbers.

**How to Find All Prime Numbers Less Than N in Python?**

Here's a simple function that finds all prime numbers less than a given integer `N` using the Sieve of Eratosthenes algorithm:

```
def sieve_of_eratosthenes(n):
    # Create a boolean array, prime[2..n], initially true for all indices
    prime = [True] * (n + 1)
    prime[0] = prime[1] = False

    # Iterate from 2 to sqrt(n)
    for p in range(2, int(n ** 0.5) + 1):
        # If p is a prime number, mark as composite all the multiples of p
        if prime[p]:
            for i in range(p * p, n + 1, p):
                prime[i] = False

    # Return a list of all prime numbers less than n
    return [p for p in range(2, n) if prime[p]]
```

Here's how the function works:

1. Create a boolean array `prime` with `n+1` elements, initialized to `True`. This represents whether each number is prime or 
not.
2. Set `prime[0] = prime[1] = False`, since 0 and 1 are not prime numbers.
3. Iterate from 2 to `sqrt(n)`, checking if each `p` is a prime number (i.e., `prime[p] == True`).
4. If `p` is a prime number, mark as composite all the multiples of `p` by setting `prime[i] = False` for `i` ranging from `p*p`
to `n+1`, incrementing by `p`.
5. Finally, return a list comprehension of all prime numbers less than `n`, using the `prime[p] == True` condition.

Here's an example usage:

```
>>> sieve_of_eratosthenes(30)
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
```

This function has a time complexity of O(n log log n) and a space complexity of O(n), making it efficient for finding prime numbers up to a certain limit.



In [1]:
def sieve_of_eratosthenes(n):
    # Create a boolean array, prime[2..n], initially true for all indices
    prime = [True] * (n + 1)
    prime[0] = prime[1] = False

    # Iterate from 2 to sqrt(n)
    for p in range(2, int(n ** 0.5) + 1):
        # If p is a prime number, mark as composite all the multiples of p
        if prime[p]:
            for i in range(p * p, n + 1, p):
                prime[i] = False

    # Return a list of all prime numbers less than n
    return [p for p in range(2, n) if prime[p]]


In [2]:
sieve_of_eratosthenes(30)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]